// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdltdJWUtPGh6gXwKiIYKhrz20WFtURZs',
    appId: '1:211095242862:web:d91d8670f682703adb3e7f',
    messagingSenderId: '211095242862',
    projectId: 'reddit-clone-2b518',
    authDomain: 'reddit-clone-2b518.firebaseapp.com',
    storageBucket: 'reddit-clone-2b518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA733es3thNHeC4nNohIVbm61On16K7pHo',
    appId: '1:211095242862:android:7774082ddfd8534adb3e7f',
    messagingSenderId: '211095242862',
    projectId: 'reddit-clone-2b518',
    storageBucket: 'reddit-clone-2b518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBYsXYTpuk2Cm25z77juZMG9UXFRADO0',
    appId: '1:211095242862:ios:84bb9b98271aad08db3e7f',
    messagingSenderId: '211095242862',
    projectId: 'reddit-clone-2b518',
    storageBucket: 'reddit-clone-2b518.appspot.com',
    iosClientId: '211095242862-ans4nljmi4ejc2pmc6o1447t40c0inu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
